### PR TITLE
Tcf 113 upload workflow

### PR DESCRIPTION
**Pull request by flori950**
Pls review asap. Merged tcf and main in my Branch and needed to fix a lot of errors.

### CODE REVIEW

**Comment by thdrbrkw** [comment]
- for all sub-components: the button to upload the data is always disabled
- for SIMRA/ CerV2 dont display coordinates field
- for json/csv/text coordinates are optional
- when drag&dropping the wrong filetype, the filename is also copied as title, but no error message displayed

**Comment by thdrbrkw** [comment]
Also, you have created seperate components with redundant code. I am not sure how I feel about it. @salbani what do you think?

**Comment by flori950** [comment]
Are you sure? Because It's much easier for routing then because we route over components, and we cannot change the URL then. I would let it like that, otherwise we need to change the whole routing.

**Comment by Corgam** [comment]
Also few notes:
- When clicking `no file`, the user should be also allowed to upload not referenced datatypes (currently only referenced are available). Just check how it was done by Theo before the current upload changes. 
- When uploading a file, inside the `title` text inside title field does not update and go to the top 
image
- Name should be shorter to fit on the screen, so maybe use: `CERv2`
image
- Unnecessary doubled text at the location on the map, instead just leave coords.
image
- Also please delete the white space at the left side of panels (the same as it is in main menu)
image

**Comment by thdrbrkw** [comment]
> Are you sure? Because It's much easier for routing then because we route over components, and we cannot change the URL then. I would let it like that, otherwise we need to change the whole routing.

Yes we could use seperate URLs: In the `app.routes` different routes link to the same component and this component retrieves the url-segments and therefore knows, if it is a CSV/ JSON/ etc. But I'm not sure if the rebuild is worth it.


> * When clicking `no file`, the user should be also allowed to upload not referenced datatypes (currently only referenced are available). Just check how it was done by Theo before the current upload changes.
Oh sorry, that was my instruction. I just assumed uploading pure text would not really happen (since we have the txt upload) and therefore said non referenced data will be fine.

**Comment by Corgam** [comment]
Looks good, two final notes:
- Arrow back takes you too far (main menu and it should be the data type menu)
- Maybe add a short note inside the dataset upload to say that the `Description and tags will be added to all created documents`.

**Review by Corgam — APPROVED** [review]

**Pull request merged**
